package JPack_Interfaz;


import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raymundo
 */
public class AccesoSistema extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public AccesoSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_SistemaAcademico = new javax.swing.JPanel();
        jLabel_Usuario = new javax.swing.JLabel();
        jTextField_Usuario = new javax.swing.JTextField();
        jLabel_Contraseña = new javax.swing.JLabel();
        jTextField_Contraseña = new javax.swing.JPasswordField();
        jButton_Ingresar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel_LogoUnamba = new javax.swing.JLabel();
        jLabel_IconoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_SistemaAcademico.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_SistemaAcademico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acceso al Sistema Academico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 14))); // NOI18N
        jPanel_SistemaAcademico.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_SistemaAcademico.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel_Usuario.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel_Usuario.setText("Usuario ");

        jTextField_Usuario.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel_Contraseña.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel_Contraseña.setText("Contraseña ");

        jTextField_Contraseña.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jButton_Ingresar.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton_Ingresar.setText("Ingresar");
        jButton_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresarActionPerformed(evt);
            }
        });

        jButton_Salir.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jLabel_LogoUnamba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Unamba.png"))); // NOI18N

        jLabel_IconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_SistemaAcademicoLayout = new javax.swing.GroupLayout(jPanel_SistemaAcademico);
        jPanel_SistemaAcademico.setLayout(jPanel_SistemaAcademicoLayout);
        jPanel_SistemaAcademicoLayout.setHorizontalGroup(
            jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SistemaAcademicoLayout.createSequentialGroup()
                .addComponent(jLabel_LogoUnamba)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jPanel_SistemaAcademicoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SistemaAcademicoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel_IconoUsuario))
                    .addComponent(jButton_Ingresar)
                    .addGroup(jPanel_SistemaAcademicoLayout.createSequentialGroup()
                        .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Usuario)
                            .addComponent(jLabel_Contraseña))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_SistemaAcademicoLayout.setVerticalGroup(
            jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SistemaAcademicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LogoUnamba)
                .addGap(18, 18, 18)
                .addComponent(jLabel_IconoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Usuario)
                    .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Contraseña)
                    .addComponent(jTextField_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SistemaAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Ingresar)
                    .addComponent(jButton_Salir))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_SistemaAcademico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_SistemaAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 492, Short.MAX_VALUE)
        );

        jPanel_SistemaAcademico.getAccessibleContext().setAccessibleName("Sistema Academico");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngresarActionPerformed
        String usuario = jTextField_Usuario.getText();
        String paswd = jTextField_Contraseña.getText();
        
        if(usuario.isEmpty() || paswd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Algún campo esta vacio");
        }else{
             if(usuario.equals("121183") && paswd.equals("47302718")){
                 JOptionPane.showMessageDialog(null,"Bienvenido");
                 JFrame_SistemaMatricula pc = new JFrame_SistemaMatricula();
                 pc.setVisible(true);
                 this.dispose();
                 
             }else
             {
                 JOptionPane.showMessageDialog(this, "Su usuario o contraseña es incorrecto", "Aviso", JOptionPane.INFORMATION_MESSAGE);
             }
        }
    }//GEN-LAST:event_jButton_IngresarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoSistema().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ingresar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_IconoUsuario;
    private javax.swing.JLabel jLabel_LogoUnamba;
    private javax.swing.JLabel jLabel_Usuario;
    private javax.swing.JPanel jPanel_SistemaAcademico;
    private javax.swing.JPasswordField jTextField_Contraseña;
    private javax.swing.JTextField jTextField_Usuario;
    // End of variables declaration//GEN-END:variables
}
