/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPack_Interfaz;


import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexion.MainConexionSQLSever;
//import Util.ClienteItem;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ALI
 */
public class JInternalFrame_RegistrosDocentes extends javax.swing.JInternalFrame {

    Connection cn;
    CallableStatement cts;
    ResultSet r;
    MainConexionSQLSever conectar = new MainConexionSQLSever();
    //Otros
    DefaultTableModel model = new DefaultTableModel();
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form JInternalFrame_Productos
     */
    public JInternalFrame_RegistrosDocentes() 
    {
        initComponents();
        cn = conectar.Conexcion();
        //Llenar_Genero();
        cargar();
        DESABILITAR();
        BOTONES();
    }

    public void cargar() 
    {

        DefaultTableModel tabla = new DefaultTableModel();
        try 
        {
            tabla.addColumn("Codigo Docente");
            tabla.addColumn("Codigo Escuela Profesional");
            tabla.addColumn("Nombres");
            tabla.addColumn("Apellidos");
            tabla.addColumn("DNI");
            tabla.addColumn("Sexo");
            tabla.addColumn("Fecha Nacimiento");            
            tabla.addColumn("Grado Academico");            
            tabla.addColumn("Categoria Docente");
            tabla.addColumn("Condicion Docente");
            cts = cn.prepareCall("{call sp_mostrardocentes}");
            r = cts.executeQuery();
            while (r.next()) 
            {
                Object dato[] = new Object[10];
                for (int i = 0; i < 10; i++) {
                    dato[i] = r.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.jTable_Docentes.setModel(tabla);

        } catch (Exception e) {
        }
    }

    public void limpiar() 
    {
        this.jTextField_Codigo.setText("");
        this.jTextField_CodEscuelaPr.setText("");
        this.jTextField_Nombre.setText("");
        this.jTextField_Apellidos.setText("");
        this.jTextField_Dni.setText("");
        this.jComboBox_Sexo.setSelectedIndex(0);
        this.jTextField_FechaNacimiento.setText("");
        this.jTextField_GradoAcademico.setText("");
        this.jTextField_CategoriaDocente.setText("");
        this.jTextField_CondicionDocente.setText(""); 
    }

    public void ABILITAR() {
//        this.jTextField_Nombre.setEnabled(true);
//        this.jTextField_Apellidos.setEnabled(true);
//        this.jComboBox_Sexo.setEnabled(true);
//        this.jTextField_Dni.setEnabled(true);
//        this.jTextField_Telefono.setEnabled(true);
//        this.jTextField_Ruc.setEnabled(true);
//        this.jTextField_Email.setEnabled(true);
//        jTextField_Direccion.setEnabled(true);
//        this.jTextField_Nombre.requestFocus();
    }

    public void DESABILITAR() {
//        this.jTextField_Nombre.setEnabled(false);
//        this.jTextField_Apellidos.setEnabled(false);
//        this.jComboBox_Sexo.setEnabled(false);
//        this.jTextField_Dni.setEnabled(false);
//        this.jTextField_Telefono.setEnabled(false);
//        this.jTextField_Ruc.setEnabled(false);
//        this.jTextField_Email.setEnabled(false);
//        jTextField_Direccion.setEnabled(false);
    }

    public void BOTONES() {
        this.jButton_Agregar.setEnabled(false);
        this.jButton_Nuevo.setEnabled(true);
        this.jButton_Buscar.setEnabled(true);
        this.jButton_Editar.setEnabled(false);
        this.jButton_Eliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_DatosAlumno = new javax.swing.JPanel();
        jLabel_Codigo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Apellidos = new javax.swing.JLabel();
        jLabel_Sexo = new javax.swing.JLabel();
        jLabel_Dni = new javax.swing.JLabel();
        jLabel_CategoriaDocente = new javax.swing.JLabel();
        jLabel_CondicionDocente = new javax.swing.JLabel();
        jTextField_Codigo = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Apellidos = new javax.swing.JTextField();
        jComboBox_Sexo = new javax.swing.JComboBox();
        jTextField_Dni = new javax.swing.JTextField();
        jTextField_CategoriaDocente = new javax.swing.JTextField();
        jTextField_FechaNacimiento = new javax.swing.JTextField();
        jLabel_FechaNacimiento = new javax.swing.JLabel();
        jLabel_GradoAcademico = new javax.swing.JLabel();
        jTextField_CondicionDocente = new javax.swing.JTextField();
        jTextField_GradoAcademico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jButton_Nuevo = new javax.swing.JButton();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel_CodEscuelaPr = new javax.swing.JLabel();
        jTextField_CodEscuelaPr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Docentes = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("REGISTRO DE DOCENTES");

        jPanel_DatosAlumno.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_DatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Docente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 0, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel_Codigo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Codigo.setText("Codigo:");

        jLabel_Nombre.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Nombre.setText("Nombre:");

        jLabel_Apellidos.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Apellidos.setText("Apellidos: ");

        jLabel_Sexo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Sexo.setText("Sexo:");

        jLabel_Dni.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Dni.setText("DNI: ");

        jLabel_CategoriaDocente.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_CategoriaDocente.setText("Categoria del Docente: ");

        jLabel_CondicionDocente.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_CondicionDocente.setText("Condicion del Docente: ");

        jTextField_Codigo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_Codigo.setEnabled(false);

        jTextField_Nombre.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NombreKeyReleased(evt);
            }
        });

        jTextField_Apellidos.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jComboBox_Sexo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jComboBox_Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..", "M", "F" }));

        jTextField_Dni.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jTextField_CategoriaDocente.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jTextField_FechaNacimiento.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel_FechaNacimiento.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_FechaNacimiento.setText("Fecha Nac.:  ");

        jLabel_GradoAcademico.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_GradoAcademico.setText("Grado Academico: ");

        jTextField_CondicionDocente.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jTextField_GradoAcademico.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Docente.jpg"))); // NOI18N

        jLabel_Bienvenida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Bienvenida.setText("Bienvenidos  ");

        jButton_Nuevo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/NuevoRegistro.png"))); // NOI18N
        jButton_Nuevo.setText("Nuevo");
        jButton_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NuevoActionPerformed(evt);
            }
        });

        jButton_Agregar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Guardar.png"))); // NOI18N
        jButton_Agregar.setText("Agregar");
        jButton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Buscar2.png"))); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Editar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Consulta.png"))); // NOI18N
        jButton_Editar.setText("Editar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/EliminarArticulo.png"))); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Cancelar23.png"))); // NOI18N
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Actualizarrrr.png"))); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        jButton_Salir.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Salir.png"))); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jLabel_CodEscuelaPr.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_CodEscuelaPr.setText("Cod. Escuela Profesional: ");

        jTextField_CodEscuelaPr.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Unamba.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_DatosAlumnoLayout = new javax.swing.GroupLayout(jPanel_DatosAlumno);
        jPanel_DatosAlumno.setLayout(jPanel_DatosAlumnoLayout);
        jPanel_DatosAlumnoLayout.setHorizontalGroup(
            jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                        .addComponent(jButton_Nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Salir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                            .addComponent(jLabel_Codigo)
                                            .addGap(47, 47, 47)
                                            .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                            .addComponent(jLabel_Nombre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                        .addComponent(jLabel_CategoriaDocente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_CategoriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_Dni)
                                        .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                            .addComponent(jLabel_FechaNacimiento)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_Apellidos)
                                        .addComponent(jLabel_CodEscuelaPr))
                                    .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                        .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_Sexo)
                                            .addComponent(jLabel_GradoAcademico)
                                            .addComponent(jLabel_CondicionDocente))
                                        .addGap(9, 9, 9)))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_GradoAcademico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_Sexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_Apellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CodEscuelaPr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CondicionDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jLabel_Bienvenida))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_DatosAlumnoLayout.setVerticalGroup(
            jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Bienvenida)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Codigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Nombre))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Dni)
                                    .addComponent(jTextField_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_FechaNacimiento))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_CategoriaDocente)
                                    .addComponent(jTextField_CategoriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_DatosAlumnoLayout.createSequentialGroup()
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_CodEscuelaPr)
                                    .addComponent(jTextField_CodEscuelaPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Apellidos)
                                    .addComponent(jTextField_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Sexo)
                                    .addComponent(jComboBox_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_GradoAcademico)
                                    .addComponent(jTextField_GradoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_CondicionDocente)
                                    .addComponent(jTextField_CondicionDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Nuevo)
                    .addComponent(jButton_Agregar)
                    .addComponent(jButton_Buscar)
                    .addComponent(jButton_Editar)
                    .addComponent(jButton_Eliminar)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_Actualizar)
                    .addComponent(jButton_Salir)))
        );

        jTable_Docentes.setBackground(new java.awt.Color(204, 204, 204));
        jTable_Docentes.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTable_Docentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Docentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_DocentesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Docentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_DatosAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_DatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_DatosAlumno.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        try {

            cts = cn.prepareCall("{call sp_generarcodigodocente}");
            r = cts.executeQuery();
            if (r.next()) {
                jTextField_Codigo.setText(r.getString(1));
            }
        } catch (Exception e) {
        }
        ABILITAR();
        this.jButton_Agregar.setEnabled(true);
        this.jButton_Nuevo.setEnabled(false);
        this.jButton_Buscar.setEnabled(false);
        this.jButton_Editar.setEnabled(false);
        this.jButton_Eliminar.setEnabled(false);

    }//GEN-LAST:event_jButton_NuevoActionPerformed

    private void jButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarActionPerformed
        // TODO add your handling code here:
        String cod = jTextField_Codigo.getText();
        String codep = jTextField_CodEscuelaPr.getText();
        String nom = jTextField_Nombre.getText();
        String ape = jTextField_Apellidos.getText();
        String dni = jTextField_Dni.getText();
        String sexo = this.jComboBox_Sexo.getSelectedItem().toString();
        String fec = jTextField_FechaNacimiento.getText();
        String graa = jTextField_GradoAcademico.getText();
        String catd = jTextField_CategoriaDocente.getText();
        String cond = jTextField_CondicionDocente.getText();
        //obtenemos el objeto grupoitem seleccionado 
        //ClienteItem genero = (ClienteItem) jComboBox_Sexo.getSelectedItem();
        //String sexo = genero.setGeneroCli(); //obtenemos valor de la clase
        try {
            cts = cn.prepareCall("{call sp_agregardocentes(?,?,?,?,?,?,?,?,?,?)}");
            cts.setString(1, cod);
            cts.setString(2, codep);
            cts.setString(3, nom);
            cts.setString(4, ape);
            cts.setString(5, dni);
            cts.setString(6, sexo);
            cts.setString(7, fec);
            cts.setString(8, graa);
            cts.setString(9, catd);
            cts.setString(10, cond);

            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Registrado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }
            BOTONES();
            DESABILITAR();
            limpiar();
            cargar();
        } catch (SQLException | HeadlessException e) {
            //Logger.getLogger(JInternalFrame_RegistroDocentes.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton_AgregarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:      
        String cod = JOptionPane.showInputDialog("Ingrese el nombre del docente");
        try {
            cts = cn.prepareCall("{call sp_buscardocentes(?)}");
            cts.setString(1, cod);
            r = cts.executeQuery();

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Docente encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.jTextField_Codigo.setText(r.getString(1));
                this.jTextField_CodEscuelaPr.setText(r.getString(2));
                this.jTextField_Nombre.setText(r.getString(3));
                this.jTextField_Apellidos.setText(r.getString(4));
                this.jTextField_Dni.setText(r.getString(5));
                this.jComboBox_Sexo.setSelectedItem(r.getString(6).toString());
                this.jTextField_FechaNacimiento.setText(r.getString(7));
                this.jTextField_GradoAcademico.setText(r.getString(8));
                this.jTextField_CategoriaDocente.setText(r.getString(9));
                this.jTextField_CondicionDocente.setText(r.getString(10));
                /*ClienteItem item; //objeto grupoitem
                //obtenemos el modelo de datos del jcomboboxx
                DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox_Sexo.getModel();
                //recorremos los objetos del jcombobox
                for (int i = 0; i < model.getSize(); i++) 
                {
                    item = (ClienteItem) model.getElementAt(i); // obtener clienteitem del indice
                    if(item.setGeneroCli().equals(r.getString(4))){
                        jComboBox_Sexo.setSelectedItem(item);
                    }
                } */
                ABILITAR();
                this.jButton_Agregar.setEnabled(false);
                this.jButton_Nuevo.setEnabled(false);
                this.jButton_Buscar.setEnabled(false);
                this.jButton_Editar.setEnabled(true);
                this.jButton_Eliminar.setEnabled(true);
            } else {

                JOptionPane.showMessageDialog(this, "Docente  no encontrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        String cod = jTextField_Codigo.getText();
        String codep = jTextField_CodEscuelaPr.getText();
        String nom = jTextField_Nombre.getText();
        String ape = jTextField_Apellidos.getText();
        String dni = jTextField_Dni.getText();
        String sexo = this.jComboBox_Sexo.getSelectedItem().toString();
        String fec = jTextField_FechaNacimiento.getText();
        String graa = jTextField_GradoAcademico.getText();
        String catd = jTextField_CategoriaDocente.getText();
        String cond = jTextField_CondicionDocente.getText();
        //ClienteItem genero = (ClienteItem) jComboBox_Sexo.getSelectedItem();
        //String sexo = genero.setGeneroCli(); //obtenemos valor de la clase

        try {
            cts = cn.prepareCall("{call sp_modificardocentes(?,?,?,?,?,?,?,?,?,?)}");
            cts.setString(1, cod);
            cts.setString(2, codep);
            cts.setString(3, nom);
            cts.setString(4, ape);
            cts.setString(5, dni);
            cts.setString(6, sexo);
            cts.setString(7, fec);
            cts.setString(8, graa);
            cts.setString(9, catd);
            cts.setString(10,cond);
            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Docente modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                DESABILITAR();
                BOTONES();
                cargar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:
        String cod = this.jTextField_Codigo.getText();
        try {
            cts = cn.prepareCall("{call sp_eliminardocentes(?)}");
            cts.setString(1, cod);
            int rpta = cts.executeUpdate();

            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Docente eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                DESABILITAR();
                BOTONES();
                cargar();
            } else {
                JOptionPane.showMessageDialog(this, "Docente no eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        BOTONES();
        DESABILITAR();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Salir", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jTable_DocentesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DocentesMousePressed
        // TODO add your handling code here:
        int filaSeleccionada = this.jTable_Docentes.getSelectedRow();//Identificamos que fila ha sido seleccionada
        try {
            this.jTextField_Codigo.setText(jTable_Docentes.getValueAt(filaSeleccionada, 0).toString());
            this.jTextField_CodEscuelaPr.setText(jTable_Docentes.getValueAt(filaSeleccionada, 1).toString());
            this.jTextField_Nombre.setText(jTable_Docentes.getValueAt(filaSeleccionada, 2).toString());
            this.jTextField_Apellidos.setText(jTable_Docentes.getValueAt(filaSeleccionada, 3).toString());
            this.jTextField_Dni.setText(jTable_Docentes.getValueAt(filaSeleccionada, 4).toString());
            this.jComboBox_Sexo.getSelectedItem().toString().equals(jTable_Docentes.getValueAt(filaSeleccionada, 5).toString());
            this.jTextField_FechaNacimiento.setText(jTable_Docentes.getValueAt(filaSeleccionada, 6).toString());
            this.jTextField_GradoAcademico.setText(jTable_Docentes.getValueAt(filaSeleccionada, 7).toString());
            this.jTextField_CategoriaDocente.setText(jTable_Docentes.getValueAt(filaSeleccionada, 8).toString());
            this.jTextField_CondicionDocente.setText(jTable_Docentes.getValueAt(filaSeleccionada, 9).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        }
        ABILITAR();
        this.jButton_Nuevo.setEnabled(true);
        this.jButton_Agregar.setEnabled(true);
        this.jButton_Buscar.setEnabled(false);
        this.jButton_Editar.setEnabled(true);
        this.jButton_Eliminar.setEnabled(true);
        this.jButton_Cancelar.setEnabled(true);
        this.jButton_Actualizar.setEnabled(true);
        this.jButton_Salir.setEnabled(true);
    }//GEN-LAST:event_jTable_DocentesMousePressed

    private void jTextField_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreKeyReleased
        // TODO add your handling code here:
        String[] titulos = {"Codigo Docente", "Codigo Escuela Prof.","Nombres","Apellidos","DNI","Sexo","Fecha Nacimiento","Grado Academico", "Categoria Docente","Condicion Docente"};
        String[] registros = new String[200];
        String sql = "SELECT * FROM tdocente WHERE NombreDocente LIKE '" + jTextField_Nombre.getText() + "%'";
        model = new DefaultTableModel(null, titulos);
        //Connection conect = ClassConection.getConexion();
        try {
            st = (Statement) cn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("CodDocente");
                registros[1] = rs.getString("CodEscuelaProfesional");
                registros[2] = rs.getString("NombreDocente");
                registros[3] = rs.getString("ApellidosDocente");
                registros[4] = rs.getString("DNIDocente");
                registros[5] = rs.getString("Sexo");
                registros[6] = rs.getString("FechaNacimiento");
                registros[7] = rs.getString("GradoAcademico");
                registros[8] = rs.getString("CategoriaDocente");
                registros[9] = rs.getString("CondicionDocente");

                model.addRow(registros);
            }
            jTable_Docentes.setModel(model);
        } catch (SQLException ex) {
            System.out.println("Error al Buscar Datos: " + ex.getMessage());
        }
    }//GEN-LAST:event_jTextField_NombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Nuevo;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JComboBox jComboBox_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_CategoriaDocente;
    private javax.swing.JLabel jLabel_CodEscuelaPr;
    private javax.swing.JLabel jLabel_Codigo;
    private javax.swing.JLabel jLabel_CondicionDocente;
    private javax.swing.JLabel jLabel_Dni;
    private javax.swing.JLabel jLabel_FechaNacimiento;
    private javax.swing.JLabel jLabel_GradoAcademico;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Sexo;
    private javax.swing.JPanel jPanel_DatosAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Docentes;
    private javax.swing.JTextField jTextField_Apellidos;
    private javax.swing.JTextField jTextField_CategoriaDocente;
    private javax.swing.JTextField jTextField_CodEscuelaPr;
    private javax.swing.JTextField jTextField_Codigo;
    private javax.swing.JTextField jTextField_CondicionDocente;
    private javax.swing.JTextField jTextField_Dni;
    private javax.swing.JTextField jTextField_FechaNacimiento;
    private javax.swing.JTextField jTextField_GradoAcademico;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
