/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPack_Interfaz;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexion.MainConexionSQLSever;
//import Util.ClienteItem;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ALI
 */
public class JInternalFrame_RegistroEscuelaProf extends javax.swing.JInternalFrame {

    Connection cn;
    CallableStatement cts;
    ResultSet r;
    MainConexionSQLSever conectar = new MainConexionSQLSever();
    //Otros
    DefaultTableModel model = new DefaultTableModel();
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form JInternalFrame_Productos
     */
    public JInternalFrame_RegistroEscuelaProf() 
    {
        initComponents();
        cn = conectar.Conexcion();
        //Llenar_Genero();
        cargar();
        DESABILITAR();
        BOTONES();
    }

    public void cargar() 
    {

        DefaultTableModel tabla = new DefaultTableModel();
        try 
        {
            tabla.addColumn("Codigo de Escuela Prof. ");
            tabla.addColumn("Codigo de Facultad");
            tabla.addColumn("Nombre de Escuela Prof.");
            tabla.addColumn("Observaciones");
            cts = cn.prepareCall("{call sp_mostrarescuelaprofesional}");
            r = cts.executeQuery();
            while (r.next()) 
            {
                Object dato[] = new Object[4];
                for (int i = 0; i < 4; i++) {
                    dato[i] = r.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.jTable_EscuelaProfesional.setModel(tabla);

        } catch (Exception e) {
        }
    }

    public void limpiar() 
    {
        this.jTextField_CodigoEscuelaProfesional.setText("");
        this.jTextField_CodigoFacultad.setText("");
        this.jTextField_NombreEscuelaProfesional.setText("");
        jTextField_Observación.setText("");
    }

    public void ABILITAR() {
//        this.jTextField_Nombre.setEnabled(true);
//        this.jTextField_Apellidos.setEnabled(true);
//        this.jComboBox_Sexo.setEnabled(true);
//        this.jTextField_Dni.setEnabled(true);
//        this.jTextField_Telefono.setEnabled(true);
//        this.jTextField_Ruc.setEnabled(true);
//        this.jTextField_Email.setEnabled(true);
//        jTextField_Direccion.setEnabled(true);
//        this.jTextField_Nombre.requestFocus();
    }

    public void DESABILITAR() {
//        this.jTextField_Nombre.setEnabled(false);
//        this.jTextField_Apellidos.setEnabled(false);
//        this.jComboBox_Sexo.setEnabled(false);
//        this.jTextField_Dni.setEnabled(false);
//        this.jTextField_Telefono.setEnabled(false);
//        this.jTextField_Ruc.setEnabled(false);
//        this.jTextField_Email.setEnabled(false);
//        jTextField_Direccion.setEnabled(false);
    }

    public void BOTONES() {
        this.jButton_Agregar.setEnabled(false);
        this.jButton_Nuevo.setEnabled(true);
        this.jButton_Buscar.setEnabled(true);
        this.jButton_Editar.setEnabled(false);
        this.jButton_Eliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_DatosEscuelaProfesional = new javax.swing.JPanel();
        jLabel_CodigoEscuelaProfesional = new javax.swing.JLabel();
        jLabel_CodigoFacultad = new javax.swing.JLabel();
        jLabel_NombreEscuelaProfesional = new javax.swing.JLabel();
        jTextField_CodigoEscuelaProfesional = new javax.swing.JTextField();
        jTextField_CodigoFacultad = new javax.swing.JTextField();
        jTextField_NombreEscuelaProfesional = new javax.swing.JTextField();
        jLabel_Observación = new javax.swing.JLabel();
        jTextField_Observación = new javax.swing.JTextField();
        jLabel_FondoEscuelaProfesional = new javax.swing.JLabel();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jButton_Nuevo = new javax.swing.JButton();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_EscuelaProfesional = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("REGISTRO DE ESCUELAS PROFESIONALES");

        jPanel_DatosEscuelaProfesional.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_DatosEscuelaProfesional.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Escuela Profesional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 0, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel_CodigoEscuelaProfesional.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_CodigoEscuelaProfesional.setText("Codigo Escuela Profesional: ");

        jLabel_CodigoFacultad.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_CodigoFacultad.setText("Codigo Facultad: ");

        jLabel_NombreEscuelaProfesional.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_NombreEscuelaProfesional.setText("Nombre Escuela Profesional: ");

        jTextField_CodigoEscuelaProfesional.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_CodigoEscuelaProfesional.setEnabled(false);

        jTextField_CodigoFacultad.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_CodigoFacultad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_CodigoFacultadKeyReleased(evt);
            }
        });

        jTextField_NombreEscuelaProfesional.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel_Observación.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Observación.setText("Observación: ");

        jTextField_Observación.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel_FondoEscuelaProfesional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/CarrerasProfesionales.jpg"))); // NOI18N

        jLabel_Bienvenida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Bienvenida.setText("Bienvenidos  ");

        jButton_Nuevo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/NuevoRegistro.png"))); // NOI18N
        jButton_Nuevo.setText("Nuevo");
        jButton_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NuevoActionPerformed(evt);
            }
        });

        jButton_Agregar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Guardar.png"))); // NOI18N
        jButton_Agregar.setText("Agregar");
        jButton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Buscar2.png"))); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Editar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Consulta.png"))); // NOI18N
        jButton_Editar.setText("Editar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/EliminarArticulo.png"))); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Cancelar23.png"))); // NOI18N
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Actualizarrrr.png"))); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        jButton_Salir.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Salir.png"))); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Unamba.png"))); // NOI18N

        jTable_EscuelaProfesional.setBackground(new java.awt.Color(204, 204, 204));
        jTable_EscuelaProfesional.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTable_EscuelaProfesional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_EscuelaProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_EscuelaProfesionalMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_EscuelaProfesional);

        javax.swing.GroupLayout jPanel_DatosEscuelaProfesionalLayout = new javax.swing.GroupLayout(jPanel_DatosEscuelaProfesional);
        jPanel_DatosEscuelaProfesional.setLayout(jPanel_DatosEscuelaProfesionalLayout);
        jPanel_DatosEscuelaProfesionalLayout.setHorizontalGroup(
            jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                                .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                                .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_CodigoEscuelaProfesional)
                                            .addComponent(jLabel_CodigoFacultad)
                                            .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                                                .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel_NombreEscuelaProfesional)
                                                    .addComponent(jLabel_Observación))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField_Observación, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField_CodigoFacultad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_CodigoEscuelaProfesional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1))
                                    .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                                        .addComponent(jButton_Nuevo)
                                        .addGap(14, 14, 14)
                                        .addComponent(jButton_Agregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Editar))))
                    .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_NombreEscuelaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(58, 58, 58)
                            .addComponent(jLabel_Bienvenida))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jLabel_FondoEscuelaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel_DatosEscuelaProfesionalLayout.setVerticalGroup(
            jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DatosEscuelaProfesionalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_Bienvenida))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CodigoEscuelaProfesional)
                            .addComponent(jTextField_CodigoEscuelaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CodigoFacultad)
                            .addComponent(jTextField_CodigoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NombreEscuelaProfesional)
                            .addComponent(jTextField_NombreEscuelaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Observación)
                            .addComponent(jTextField_Observación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Nuevo)
                            .addComponent(jButton_Agregar)
                            .addComponent(jButton_Buscar)
                            .addComponent(jButton_Editar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_DatosEscuelaProfesionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Salir)
                            .addComponent(jButton_Actualizar)
                            .addComponent(jButton_Cancelar)
                            .addComponent(jButton_Eliminar)))
                    .addComponent(jLabel_FondoEscuelaProfesional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_DatosEscuelaProfesional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_DatosEscuelaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_DatosEscuelaProfesional.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        try {

            cts = cn.prepareCall("{call sp_generarcodigoescuelaprofesional}");
            r = cts.executeQuery();
            if (r.next()) {
                jTextField_CodigoEscuelaProfesional.setText(r.getString(1));
            }
        } catch (Exception e) {
        }
        ABILITAR();
        this.jButton_Agregar.setEnabled(true);
        this.jButton_Nuevo.setEnabled(false);
        this.jButton_Buscar.setEnabled(false);
        this.jButton_Editar.setEnabled(false);
        this.jButton_Eliminar.setEnabled(false);

    }//GEN-LAST:event_jButton_NuevoActionPerformed

    private void jButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarActionPerformed
        // TODO add your handling code here:
        String codep = jTextField_CodigoEscuelaProfesional.getText();
        String codf = jTextField_CodigoFacultad.getText();
        String nombep = jTextField_NombreEscuelaProfesional.getText();
        String obs = jTextField_Observación.getText();
        try {
            cts = cn.prepareCall("{call sp_agregarescuelaprofesional(?,?,?,?)}");
            cts.setString(1, codep);
            cts.setString(2, codf);
            cts.setString(3, nombep);
            cts.setString(4, obs);

            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Registrado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }
            BOTONES();
            DESABILITAR();
            limpiar();
            cargar();
        } catch (SQLException | HeadlessException e) {
            Logger.getLogger(JInternalFrame_RegistroEscuelaProf.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton_AgregarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:      
        String codep = JOptionPane.showInputDialog("Ingrese el nombre de la escuela profesional ");
        try {
            cts = cn.prepareCall("{call sp_buscarescuelaprofesional(?)}");
            cts.setString(1, codep);
            r = cts.executeQuery();

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Escuela Profesional encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.jTextField_CodigoEscuelaProfesional.setText(r.getString(1));
                this.jTextField_CodigoFacultad.setText(r.getString(2));
                this.jTextField_NombreEscuelaProfesional.setText(r.getString(3));
                this.jTextField_Observación.setText(r.getString(4));
                
                ABILITAR();
                this.jButton_Agregar.setEnabled(false);
                this.jButton_Nuevo.setEnabled(false);
                this.jButton_Buscar.setEnabled(false);
                this.jButton_Editar.setEnabled(true);
                this.jButton_Eliminar.setEnabled(true);
            } else {

                JOptionPane.showMessageDialog(this, "Escuela Profesional  no encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        String codep = jTextField_CodigoEscuelaProfesional.getText();
        String codf = jTextField_CodigoFacultad.getText();
        String nombep = jTextField_NombreEscuelaProfesional.getText();
        String obs = jTextField_Observación.getText();

        try {
            cts = cn.prepareCall("{call sp_modificarescuelaprofesional(?,?,?,?)}");
            cts.setString(1, codep);
            cts.setString(2, codf);
            cts.setString(3, nombep);
            cts.setString(4, obs);
            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Escuela Profesional modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                DESABILITAR();
                BOTONES();
                cargar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:
        String codep = this.jTextField_CodigoEscuelaProfesional.getText();
        try {
            cts = cn.prepareCall("{call sp_eliminarescuelaprofesional(?)}");
            cts.setString(1, codep);
            int rpta = cts.executeUpdate();

            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "La Escuela Profesional a sido eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                DESABILITAR();
                BOTONES();
                cargar();
            } else {
                JOptionPane.showMessageDialog(this, "La Escuela Profesional no se pudo eliminar", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        BOTONES();
        DESABILITAR();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Salir", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jTable_EscuelaProfesionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EscuelaProfesionalMousePressed
        // TODO add your handling code here:
        int filaSeleccionada = this.jTable_EscuelaProfesional.getSelectedRow();//Identificamos que fila ha sido seleccionada
        try {
            this.jTextField_CodigoEscuelaProfesional.setText(jTable_EscuelaProfesional.getValueAt(filaSeleccionada, 0).toString());
            this.jTextField_CodigoFacultad.setText(jTable_EscuelaProfesional.getValueAt(filaSeleccionada, 1).toString());
            this.jTextField_NombreEscuelaProfesional.setText(jTable_EscuelaProfesional.getValueAt(filaSeleccionada, 2).toString());
            this.jTextField_Observación.setText(jTable_EscuelaProfesional.getValueAt(filaSeleccionada, 3).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        }
        ABILITAR();
        this.jButton_Nuevo.setEnabled(true);
        this.jButton_Agregar.setEnabled(true);
        this.jButton_Buscar.setEnabled(false);
        this.jButton_Editar.setEnabled(true);
        this.jButton_Eliminar.setEnabled(true);
        this.jButton_Cancelar.setEnabled(true);
        this.jButton_Actualizar.setEnabled(true);
        this.jButton_Salir.setEnabled(true);
    }//GEN-LAST:event_jTable_EscuelaProfesionalMousePressed

    private void jTextField_CodigoFacultadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CodigoFacultadKeyReleased
        // TODO add your handling code here:
        String[] titulos = {"Codigo de Escuela Prof.", "Codigo de Facultad", "Nombre de Escuela Prof.", "Observaciones"};
        String[] registros = new String[200];
        String sql = "SELECT * FROM tescuelaprofesional WHERE NomEscuelaProfesional LIKE '" + jTextField_CodigoFacultad.getText() + "%'";
        model = new DefaultTableModel(null, titulos);
        //Connection conect = ClassConection.getConexion();
        try {
            st = (Statement) cn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("CodEscuelaProfesional");
                registros[1] = rs.getString("CodFacultad");
                registros[2] = rs.getString("NomEscuelaProfesional");
                registros[3] = rs.getString("Observación");
                model.addRow(registros);
            }
            jTable_EscuelaProfesional.setModel(model);
        } catch (SQLException ex) {
            System.out.println("Error al Buscar Datos : " + ex.getMessage());
        }
    }//GEN-LAST:event_jTextField_CodigoFacultadKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Nuevo;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_CodigoEscuelaProfesional;
    private javax.swing.JLabel jLabel_CodigoFacultad;
    private javax.swing.JLabel jLabel_FondoEscuelaProfesional;
    private javax.swing.JLabel jLabel_NombreEscuelaProfesional;
    private javax.swing.JLabel jLabel_Observación;
    private javax.swing.JPanel jPanel_DatosEscuelaProfesional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_EscuelaProfesional;
    private javax.swing.JTextField jTextField_CodigoEscuelaProfesional;
    private javax.swing.JTextField jTextField_CodigoFacultad;
    private javax.swing.JTextField jTextField_NombreEscuelaProfesional;
    private javax.swing.JTextField jTextField_Observación;
    // End of variables declaration//GEN-END:variables
}
