/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPack_Interfaz;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexion.MainConexionSQLSever;
//import Util.ClienteItem;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ALI
 */
public class JInternalFrame_RegistroAsignatura extends javax.swing.JInternalFrame {

    Connection cn;
    CallableStatement cts;
    ResultSet r;
    MainConexionSQLSever conectar = new MainConexionSQLSever();
    //Otros
    DefaultTableModel model = new DefaultTableModel();
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form JInternalFrame_Productos
     */
    public JInternalFrame_RegistroAsignatura() 
    {
        initComponents();
        cn = conectar.Conexcion();
        //Llenar_Genero();
        cargar();
        DESABILITAR();
        BOTONES();
    }

    public void cargar() 
    {

        DefaultTableModel tabla = new DefaultTableModel();
        try 
        {
            tabla.addColumn("Codigo de Asignatura");
            tabla.addColumn("Nombre de Asignatura");
            tabla.addColumn("Numero de Creditos");
            tabla.addColumn("Horas Teoricas");
            tabla.addColumn("Horas Practicas");            
            tabla.addColumn("Horas de Laboratorio");            
            tabla.addColumn("Categoria de la Asignatura");
            cts = cn.prepareCall("{call sp_mostrarasignatura}");
            r = cts.executeQuery();
            while (r.next()) 
            {
                Object dato[] = new Object[7];
                for (int i = 0; i < 7; i++) {
                    dato[i] = r.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            this.jTable_Asignaturas.setModel(tabla);

        } catch (Exception e) {
        }
    }

    public void limpiar() 
    {
        this.jTextField_Codigo.setText("");
        this.jTextField_Nombre.setText("");
        this.jTextField_NumeroCretidos.setText("");
        this.jTextField_HorasTeoricas.setText("");
        this.jTextField_HorasPracticas.setText("");
        this.jTextField_HorasLaboratorio.setText("");
        this.jTextField_CategoriaAsignaturas.setText("");
    }

    public void ABILITAR() {
//        this.jTextField_Nombre.setEnabled(true);
//        this.jTextField_Apellidos.setEnabled(true);
//        this.jComboBox_Sexo.setEnabled(true);
//        this.jTextField_Dni.setEnabled(true);
//        this.jTextField_Telefono.setEnabled(true);
//        this.jTextField_Ruc.setEnabled(true);
//        this.jTextField_Email.setEnabled(true);
//        jTextField_Direccion.setEnabled(true);
//        this.jTextField_Nombre.requestFocus();
    }

    public void DESABILITAR() {
//        this.jTextField_Nombre.setEnabled(false);
//        this.jTextField_Apellidos.setEnabled(false);
//        this.jComboBox_Sexo.setEnabled(false);
//        this.jTextField_Dni.setEnabled(false);
//        this.jTextField_Telefono.setEnabled(false);
//        this.jTextField_Ruc.setEnabled(false);
//        this.jTextField_Email.setEnabled(false);
//        jTextField_Direccion.setEnabled(false);
    }

    public void BOTONES() {
        this.jButton_Agregar.setEnabled(false);
        this.jButton_Nuevo.setEnabled(true);
        this.jButton_Buscar.setEnabled(true);
        this.jButton_Editar.setEnabled(false);
        this.jButton_Eliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_DatosAsignatura = new javax.swing.JPanel();
        jLabel_Codigo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_CategoriaAsignaturas = new javax.swing.JLabel();
        jLabel_NumeroCretidos = new javax.swing.JLabel();
        jLabel_HorasLaboratorio = new javax.swing.JLabel();
        jTextField_Codigo = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_CategoriaAsignaturas = new javax.swing.JTextField();
        jTextField_NumeroCretidos = new javax.swing.JTextField();
        jTextField_HorasLaboratorio = new javax.swing.JTextField();
        jLabel_HorasTeoricas = new javax.swing.JLabel();
        jTextField_HorasTeoricas = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jButton_Nuevo = new javax.swing.JButton();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Asignaturas = new javax.swing.JTable();
        jLabel_HorasPracticas = new javax.swing.JLabel();
        jTextField_HorasPracticas = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("REGISTRO DE ASIGNATURAS");

        jPanel_DatosAsignatura.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_DatosAsignatura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Asignatura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 0, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel_Codigo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Codigo.setText("Codigo de Asignatura: ");

        jLabel_Nombre.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_Nombre.setText("Nombre de Asignatura: ");

        jLabel_CategoriaAsignaturas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_CategoriaAsignaturas.setText("Categoria de la Asignatura: ");

        jLabel_NumeroCretidos.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_NumeroCretidos.setText("Numero Cretidos: ");

        jLabel_HorasLaboratorio.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_HorasLaboratorio.setText("Horas de Laboratorio:");

        jTextField_Codigo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_Codigo.setEnabled(false);

        jTextField_Nombre.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NombreKeyReleased(evt);
            }
        });

        jTextField_CategoriaAsignaturas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jTextField_NumeroCretidos.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jTextField_HorasLaboratorio.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel_HorasTeoricas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_HorasTeoricas.setText("Horas Teoricas: ");

        jTextField_HorasTeoricas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Asignaturas.jpg"))); // NOI18N

        jLabel_Bienvenida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Bienvenida.setText("Bienvenidos  ");

        jButton_Nuevo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/NuevoRegistro.png"))); // NOI18N
        jButton_Nuevo.setText("Nuevo");
        jButton_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NuevoActionPerformed(evt);
            }
        });

        jButton_Agregar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Guardar.png"))); // NOI18N
        jButton_Agregar.setText("Agregar");
        jButton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Buscar2.png"))); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Editar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Consulta.png"))); // NOI18N
        jButton_Editar.setText("Editar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Eliminar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/EliminarArticulo.png"))); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Cancelar23.png"))); // NOI18N
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Actualizarrrr.png"))); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        jButton_Salir.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Salir.png"))); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Unamba.png"))); // NOI18N

        jTable_Asignaturas.setBackground(new java.awt.Color(204, 204, 204));
        jTable_Asignaturas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTable_Asignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Asignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_AsignaturasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Asignaturas);

        jLabel_HorasPracticas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel_HorasPracticas.setText("Horas Practicas: ");

        jTextField_HorasPracticas.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel_DatosAsignaturaLayout = new javax.swing.GroupLayout(jPanel_DatosAsignatura);
        jPanel_DatosAsignatura.setLayout(jPanel_DatosAsignaturaLayout);
        jPanel_DatosAsignaturaLayout.setHorizontalGroup(
            jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Bienvenida))
                    .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NumeroCretidos)
                            .addComponent(jLabel_HorasTeoricas)
                            .addComponent(jLabel_HorasPracticas))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_HorasPracticas, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jTextField_HorasTeoricas)
                            .addComponent(jTextField_NumeroCretidos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                                .addComponent(jLabel_CategoriaAsignaturas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_CategoriaAsignaturas))
                            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                                .addComponent(jLabel_HorasLaboratorio)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField_HorasLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabel_Codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Nombre)
                            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                                .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                .addComponent(jButton_Nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Salir)
                .addContainerGap(126, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel_DatosAsignaturaLayout.setVerticalGroup(
            jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel))
                    .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_Bienvenida))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Codigo)
                            .addComponent(jTextField_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Nombre)
                                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_NumeroCretidos)
                                    .addComponent(jTextField_NumeroCretidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_HorasTeoricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_HorasTeoricas)))
                            .addGroup(jPanel_DatosAsignaturaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_HorasLaboratorio)
                                    .addComponent(jTextField_HorasLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_CategoriaAsignaturas)
                                    .addComponent(jTextField_CategoriaAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_HorasPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_HorasPracticas))))
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel_DatosAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Nuevo)
                    .addComponent(jButton_Agregar)
                    .addComponent(jButton_Buscar)
                    .addComponent(jButton_Editar)
                    .addComponent(jButton_Eliminar)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_Actualizar)
                    .addComponent(jButton_Salir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_DatosAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_DatosAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_DatosAsignatura.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        try {

            cts = cn.prepareCall("{call sp_generarcodigoasignatura}");
            r = cts.executeQuery();
            if (r.next()) {
                jTextField_Codigo.setText(r.getString(1));
            }
        } catch (Exception e) {
        }
        ABILITAR();
        this.jButton_Agregar.setEnabled(true);
        this.jButton_Nuevo.setEnabled(false);
        this.jButton_Buscar.setEnabled(false);
        this.jButton_Editar.setEnabled(false);
        this.jButton_Eliminar.setEnabled(false);

    }//GEN-LAST:event_jButton_NuevoActionPerformed

    private void jButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarActionPerformed
        // TODO add your handling code here:
        String cod = jTextField_Codigo.getText();
        String nom = jTextField_Nombre.getText();
        String nrc = jTextField_NumeroCretidos.getText();
        String ht = jTextField_HorasTeoricas.getText();
        String hp = jTextField_HorasPracticas.getText();
        String hl = jTextField_HorasLaboratorio.getText();
        String ctga = jTextField_CategoriaAsignaturas.getText();
        try {
            cts = cn.prepareCall("{call sp_agregarasignatura(?,?,?,?,?,?,?)}");
            cts.setString(1, cod);
            cts.setString(2, nom);
            cts.setString(3, nrc);
            cts.setString(4, ht);
            cts.setString(5, hp);
            cts.setString(6, hl);
            cts.setString(7, ctga);
            
            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Registrado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }
            BOTONES();
            DESABILITAR();
            limpiar();
            cargar();
        } catch (SQLException | HeadlessException e) {
            Logger.getLogger(JInternalFrame_RegistroAsignatura.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton_AgregarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:      
        String cod = JOptionPane.showInputDialog("Ingrese el nombre de la asignatura");
        try {
            cts = cn.prepareCall("{call sp_buscarasignatura(?)}");
            cts.setString(1, cod);
            r = cts.executeQuery();

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Asignatura encontrada!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.jTextField_Codigo.setText(r.getString(1));
                this.jTextField_Nombre.setText(r.getString(2));
                this.jTextField_NumeroCretidos.setText(r.getString(3));
                this.jTextField_HorasTeoricas.setText(r.getString(4));
                this.jTextField_HorasPracticas.setText(r.getString(5));
                this.jTextField_HorasLaboratorio.setText(r.getString(6));
                this.jTextField_CategoriaAsignaturas.setText(r.getString(7));
                
                ABILITAR();
                this.jButton_Agregar.setEnabled(false);
                this.jButton_Nuevo.setEnabled(false);
                this.jButton_Buscar.setEnabled(false);
                this.jButton_Editar.setEnabled(true);
                this.jButton_Eliminar.setEnabled(true);
            } else {

                JOptionPane.showMessageDialog(this, "Asignatura no encontrada", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        String cod = jTextField_Codigo.getText();
        String nom = jTextField_Nombre.getText();
        String nrc = jTextField_NumeroCretidos.getText();
        String ht = jTextField_HorasTeoricas.getText();
        String hp = jTextField_HorasPracticas.getText();
        String hl = jTextField_HorasLaboratorio.getText();
        String ctga = jTextField_CategoriaAsignaturas.getText();

        try {
            cts = cn.prepareCall("{call sp_modificarasignatura(?,?,?,?,?,?,?)}");
            cts.setString(1, cod);
            cts.setString(2, nom);
            cts.setString(3, nrc);
            cts.setString(4, ht);
            cts.setString(5, hp);
            cts.setString(6, hl);
            cts.setString(7, ctga);
            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Asignatura modificada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                DESABILITAR();
                BOTONES();
                cargar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:
        String cod = this.jTextField_Codigo.getText();
        try {
            cts = cn.prepareCall("{call sp_eliminarasignatura(?)}");
            cts.setString(1, cod);
            int rpta = cts.executeUpdate();

            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Asignatura eliminada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                DESABILITAR();
                BOTONES();
                cargar();
            } else {
                JOptionPane.showMessageDialog(this, "Asignatura no eliminada", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        BOTONES();
        DESABILITAR();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        // TODO add your handling code here:
        cargar();
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "Realmente desea Salir", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jTable_AsignaturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_AsignaturasMousePressed
        // TODO add your handling code here:
        int filaSeleccionada = this.jTable_Asignaturas.getSelectedRow();//Identificamos que fila ha sido seleccionada
        try {
            this.jTextField_Codigo.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 0).toString());
            this.jTextField_Nombre.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 1).toString());
            this.jTextField_NumeroCretidos.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 2).toString());
            this.jTextField_HorasTeoricas.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 3).toString());
            this.jTextField_HorasPracticas.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 4).toString());
            this.jTextField_HorasLaboratorio.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 5).toString());
            this.jTextField_CategoriaAsignaturas.setText(jTable_Asignaturas.getValueAt(filaSeleccionada, 6).toString());

        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        }
        ABILITAR();
        this.jButton_Nuevo.setEnabled(true);
        this.jButton_Agregar.setEnabled(true);
        this.jButton_Buscar.setEnabled(false);
        this.jButton_Editar.setEnabled(true);
        this.jButton_Eliminar.setEnabled(true);
        this.jButton_Cancelar.setEnabled(true);
        this.jButton_Actualizar.setEnabled(true);
        this.jButton_Salir.setEnabled(true);
    }//GEN-LAST:event_jTable_AsignaturasMousePressed

    private void jTextField_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreKeyReleased
        // TODO add your handling code here:
        String[] titulos = {"Codigo Asignatura", "Nombre de la Asignatura", "Numero de Creditos", "Horas Teoricas", "Horas Practicas", "Horas de Laboratorio", "Categoria Asignatura"};
        String[] registros = new String[200];
        String sql = "SELECT * FROM tasignatura WHERE NombreAsignatura LIKE '" + jTextField_Nombre.getText() + "%'";
        model = new DefaultTableModel(null, titulos);
        //Connection conect = ClassConection.getConexion();
        try {
            st = (Statement) cn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("CodAsignatura");
                registros[1] = rs.getString("NombreAsignatura");
                registros[2] = rs.getString("NumeroCreditos");
                registros[3] = rs.getString("HorasTeoricas");
                registros[4] = rs.getString("HorasPractica");
                registros[5] = rs.getString("HorasLaboratorio");
                registros[6] = rs.getString("CategoriaAsignatura");
                model.addRow(registros);
            }
            jTable_Asignaturas.setModel(model);
        } catch (SQLException ex) {
            System.out.println("Error al Buscar Datos : " + ex.getMessage());
        }
    }//GEN-LAST:event_jTextField_NombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Agregar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Nuevo;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_CategoriaAsignaturas;
    private javax.swing.JLabel jLabel_Codigo;
    private javax.swing.JLabel jLabel_HorasLaboratorio;
    private javax.swing.JLabel jLabel_HorasPracticas;
    private javax.swing.JLabel jLabel_HorasTeoricas;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_NumeroCretidos;
    private javax.swing.JPanel jPanel_DatosAsignatura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Asignaturas;
    private javax.swing.JTextField jTextField_CategoriaAsignaturas;
    private javax.swing.JTextField jTextField_Codigo;
    private javax.swing.JTextField jTextField_HorasLaboratorio;
    private javax.swing.JTextField jTextField_HorasPracticas;
    private javax.swing.JTextField jTextField_HorasTeoricas;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_NumeroCretidos;
    // End of variables declaration//GEN-END:variables
}
