/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JPack_Interfaz;
//Librerias
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import javax.swing.JTextField;

/// Otras Librerias
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Conexion.MainConexionSQLSever;

/**
 *
 * @author ALI
 */
public class JInternalFrame_DocentesporEscuelaProf extends javax.swing.JInternalFrame 
{
    
    //OTrosss
    Connection cn;
    CallableStatement cts;
    ResultSet r;
    MainConexionSQLSever conectar = new MainConexionSQLSever();
      
    //Otros
    DefaultTableModel model = new DefaultTableModel();  
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null; 

    /**
     * Creates new form JInternalFrame_BusGrupos
     */
    public JInternalFrame_DocentesporEscuelaProf() 
    {
        initComponents();
        cn = conectar.Conexcion();
        cargar();
    }
    private void cargar() {

        DefaultTableModel tabla = new DefaultTableModel();
        try {
            tabla.addColumn("Escuela Profesional");
            tabla.addColumn("Codigo de Escuela Prof.");
            tabla.addColumn("Numero de Docentes");
            
            cts = cn.prepareCall("{call sp_docentesporescuelapropf}");
            r = cts.executeQuery();
            while (r.next()) {
                Object dato[] = new Object[3];
                for (int i = 0; i < 3; i++) 
                {
                    dato[i] = r.getString(i + 1);

                }
                tabla.addRow(dato);
            }
            this.jTable_AlumnosMatriculados.setModel(tabla);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Busqueda = new javax.swing.JLabel();
        jTextField_BuscarAlumnos = new javax.swing.JTextField();
        jScrollPane_Tabla = new javax.swing.JScrollPane();
        jTable_AlumnosMatriculados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("ALUMNOS MATRICULADOS");

        jLabel_Busqueda.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_Busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_Imagenes/Buscar2.png"))); // NOI18N
        jLabel_Busqueda.setText("Buscar: ");

        jTextField_BuscarAlumnos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jTextField_BuscarAlumnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_BuscarAlumnosKeyReleased(evt);
            }
        });

        jTable_AlumnosMatriculados.setBackground(new java.awt.Color(204, 204, 204));
        jTable_AlumnosMatriculados.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTable_AlumnosMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Tabla.setViewportView(jTable_AlumnosMatriculados);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Lista de Alumnos Matriculados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Busqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_BuscarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Busqueda)
                    .addComponent(jTextField_BuscarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_BuscarAlumnosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BuscarAlumnosKeyReleased
        // TODO add your handling code here:

        String[] titulos = {"Id. Matricula", "Codigo Semestre","Codigo Alumno","Nombre","Apellidos","Fecha Matricula"};
        String[] registros = new String[200];
        String sql = "Select * From talumno Where NombreAlumno LIKE '%"+jTextField_BuscarAlumnos.getText()+"%'";
        model = new DefaultTableModel(null, titulos);
        //Connection conect = ClassConection.getConexion();
        try
        {
            st = (Statement) cn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next())
            {
                registros[0] = rs.getString("CodAlumno");
                registros[1] = rs.getString("NombreAlumno");
                registros[2] = rs.getString("ApellidosAlumno");
                registros[3] = rs.getString("DNIAlumno");
                registros[4] = rs.getString("FechaNacimiento");
                registros[5] = rs.getString("DireccionAlumno");
                registros[6] = rs.getString("Sexo");
                registros[7] = rs.getString("TelefonoAlumno");
                registros[8] = rs.getString("EstadoAlumno");

                model.addRow(registros);
            }
            jTable_AlumnosMatriculados.setModel(model);
        } catch (SQLException ex)
        {
            System.out.println("Error al Buscar los datos: " + ex.getMessage());
        }

    }//GEN-LAST:event_jTextField_BuscarAlumnosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Busqueda;
    private javax.swing.JScrollPane jScrollPane_Tabla;
    private javax.swing.JTable jTable_AlumnosMatriculados;
    private javax.swing.JTextField jTextField_BuscarAlumnos;
    // End of variables declaration//GEN-END:variables
}
